version: '3.5'

services:

  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar
    ports:
      - '8080:8080'
      - '6650:6650'
    expose:
      - 8080
      - 6650
    environment:
      PULSAR_MEM: " -Xms8g -Xmx8g -XX:MaxDirectMemorySize=8g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"

  pulsar-express:
    container_name: pulsar-express
    image: bbonnin/pulsar-express
    depends_on:
      - pulsar
    ports:
      - '3000:3000'
    environment:
      SERVICE_URL: http://pulsar:8080

networks:
  default:
    name: pulsar-network
    driver: bridge